services: 

  db: 
    image: mysql:8
    container_name: mym_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formmym
      MYSQL_USER: dieguitoYlasBasecitas
      MYSQL_PASSWORD: AaS9LDtGr30y73fIFXAs
  
    ports: 
      - "3306:3306" 

    volumes:
      - db_data:/var/lib/mysql
        
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p240901"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    container_name: mym_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:240901@db:3306/flyermym
      BASE_URL: http://192.168.10.16:6005
      PORT: 3001
      JWT_SECRET: CQzcP8cZlcYulBMEJAUkh8My680YWocj6glt6fuLQSJ
    
    volumes:
      - ./Backend/uploads:/app/uploads
    
    depends_on:
      - db
  
  frontend: 
    build: ./frontend
    container_name: mym_frontend
    restart: always
    ports:
      - "3000:3000"
    
    environment:
      BACKEND_INTERNAL_URL: http://backend:3001
      NEXT_PUBLIC_BACKEND_API_URL: http://192.168.10.16:3001

    depends_on:
      - backend

volumes:
  db_data:
