services: 
  db: 
    image: mysql:8
    container_name: mym_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql
        
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    image: consentimiento-backend:${BACKEND_VERSION:-v1.2026.0}
    build: 
      context: ./backend
    
    container_name: consentimientomym_backend
    restart: always
    ports:
      - "4000:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    
    volumes:
      - ./backend/uploads:/app/uploads
    
    depends_on:
      db: 
        condition: service_healthy
  
  frontend: 
    image: consentimiento-frontend:${FRONTEND_VERSION:-v1.2026.0}
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
    
    container_name: consentimientomym_frontend
    restart: always
    ports:
      - "3000:3000"
    
    environment:
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL}

    depends_on:
      - backend
  
  dashboard:
    image: consentimiento-dashboard:${DASHBOARD_VERSION:-v1.2026.0}
    build: 
      context: ./dashboard
      args:
        NEXT_PUBLIC_BACKEND_API_URL: ${NEXT_PUBLIC_BACKEND_API_URL}
    
    container_name: consentimientomym_dashboard
    restart: always
    ports:
      - "4001:3000"
    
    environment:
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL}

    depends_on:
      - backend

volumes:
  db_data: